version: "3.8"

services:
  postgres: 
    image: postgres:15.2
    restart: always
    port: 
      - "5432:5432"
    environment:
      - DATABASE_HOST = 0.0.0.0
      - POSTGRES_USER=rot
      - POSTGRES_PASSWORD= root
      - POSTGRES_DB= root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  


